version: '3'

services:
  frontend:

    container_name: frontend_app 
    restart: always 
    dockerfile: ./Dockerfile
    build:
      context: . 
    ports: 
      - "3000:3000"
    command: npm start 

  